name: PlayerShops
version: ${version}
main: de.eindaniel.playerShops.Main
authors:
  - eindaniel (Entwickler)
  - Cytooxien (Idee von deren Spielershops)
api-version: '1.21'
dependencies:
  server:
    Economy:
      required: true
      load: BEFORE