name: PlayerShops
version: '${version}'
main: de.eindaniel.playerShops.Main
authors:
  - eindaniel
  - Cytooxien (Idee)
description: "Spielershops – inspiriert von Cytooxien.net"
website: "https://github.com/eindaniels/PlayerShops"
api-version: '1.20'
depend:
  - Vault

commands:
  createshop:
    description: Erstellt einen neuen Spielershop.
    usage: /createshop <Verkaufspreis> <Ankaufspreis> <Menge>
    permission: playershop.create
  removeshop:
    description: Entfernt deinen Spielershop.
    usage: /removeshop
    permission: playershop.remove

permissions:
  playershop.create:
    description: "Erlaubt das Erstellen eines Spielershops."
    default: true
  playershop.remove:
    description: "Erlaubt das Entfernen des eigenen Spielershops."
    default: true
  playershop.admin:
    description: "Erlaubt Admin-Funktionen."
    default: op
